name: Specify User Story Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  specify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Specify check
        run: npx specify check
